language: node_js
node_js:
- iojs
- '8'
script:
- echo $GH_PAGES_TOKEN
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_PAGES_TOKEN
  keep-history: true
  on:
    branch: master

env:
  global:
  - secure: DuM6awKhEd2eudj/SQr2Cy1qO79fFlCH1nhWN3fqMmlMAHmbxdRZVFFEt907LTuZAYHoLX1tiXaf1rzKxS+sBBJWEO7hP8GCu8PQpLYmHpl2v1KXGuBxTcOd8UH/pq6BDjtT09utIGTwwx/x43XzLqVmxZ13IK4O9S7DqgPePZYjqytvNtaa7PiobG+C626lWzEPSGEH2zkGk5MvAzaNtxY7dWXHefmctsD/M9KZ1mHeDeVRvuCMdNGC8mkN+6lyg0ySWppVI/AlFsn1TjWd0id8KibrTxrFKJsc9IeiVh5rdcvPXiXgpY8QLNiPeJcZq3IHWiewZvJe42A3wXkXWTmovkKt7v9QF2TVjGg/lQb6olbAs8qScLBz2a0IS+BvSJlO98o0BAVHa7CWVqs1pqEvZRwmXR/VL/CSQ/pHE+cnmA807O0pKJJSzIWXgEZ+sjNcbKUjrvJU4Pe3jRrmTD2gbfHfZ/NuKQNb9nNGihR4VOwLJXBjvSiubXHGXs5MXOiSK43g2w2dQULmC9JoRjdP9mgXftYbz2a/NQT9LLULLPRuWZrbm5fp+cA1a520Rx4AFKje4VXIoMRQZxORuSR6kH+jAuBEKjmDrLSXR2CcCm7M0So4aIa8365zWEEwoPmcRG7sTcgcCQgVNF0fh85AVgI7Nd4x9lU3VarKs7M=