language: node_js
node_js:
- iojs
- '8'
script:
- echo $GH_PAGES_TOKEN
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "72bdbf3444f65124eeb97bea75ebddb8965c4a1a"
  keep-history: true
  on:
    branch: master