language: node_js
node_js:
- iojs
- '8'
script:
- echo $GH_PAGES_TOKEN
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 71eeab16be600e5ea04eadaf04dda1da0b56e05f
  keep-history: true
  on:
    branch: master