language: node_js
node_js:
  - "iojs"
  - "8"

script:
  - echo $GHPages_Token

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 8a95aa1a1a0bd4d86899f9959728d368bb072088
  keep-history: true
  on:
    branch: master

env:
  global:
    - $GHPages_Token=8a95aa1a1a0bd4d86899f9959728d368bb072088