language: node_js
node_js:
- iojs
- '8'
script:
- echo $GH_PAGES_TOKEN
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_PAGES_TOKEN
  keep-history: true
  on:
    branch: master
env:
  global:
  - secure: jr1WTpFbzbw1CL5FBQe76GE7RtQbkzTZUU4yrF7gPVo23zbNScZkIT7Hq3c7KGoWIwdQU+37oZjWxIppsi4ufQ1AbInbo+vYAtXRIJ+5ob4cK/w2tEMUBGCl9Spe0s36itMLLV3m0KswPD6jJEDnU4/IWoOhO4P3gf9Zh/KXZmZHpJWluimDw9jgX7kiWUxzyCr4VlNolhPJ/IdEyTsNjzakdOgtRBBBUj+JYouhAwLR2HLG7SOi+guYvjFhAvNyYh1LtsvchvCZJZGT228gpDZhryp+S1CFdNdk97RQgPHZdLJ6bGvrMC7xUSSi4Anq5AiyiKZ3gzFQOPa5Fa9tspGSSj3Bu4eU0xSiHOn6EN9X1nM5gGVGGEqpEIS1Rc9P3w1CPCLITTOX4xP8wf9MufI/4KPZ+vZBRlDuHZSFpKs5ryA35yhBCFYFPLEO/4jEb//mnVafLN0uc2Mhhz49wxZTxpNIITDaxTRj8/hdTmFvWhnGs9gnXlDN7AQFvbARlkH9j/Nvw9N9JIgbuwP05dAieol8e+/CHm8a5NG3gd21S9UT7ZA/jmBWeohPUcl2WfLjmY2FNQeme20+TB2gWVAJ6StxOec0Eo9pUD/R4w/MPa3V11QhO0dP6d43EKN+YjjdUiTnZp4pPrHICQkt6wZtSTFJOrOAyQqnLhqm2Z4=
